name: kte
description: "Flutter Course Projects"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.4
  cloud_firestore: ^5.6.2
  shared_preferences: ^2.5.4
  supabase_flutter: ^2.8.1
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Sans
      fonts:
        - asset: assets/fonts/GoogleSans-SemiBold.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf

  assets:
    - assets/images/
