// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTho5UlN1om5mv1shEe3rFNkzYvPD2hP0',
    appId: '1:832631802196:web:22454f214b5818cfed20c1',
    messagingSenderId: '832631802196',
    projectId: 'kte-lms',
    authDomain: 'kte-lms.firebaseapp.com',
    storageBucket: 'kte-lms.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC35e7PrpcR7D08e0WHRszrVQiiCOmzOA4',
    appId: '1:832631802196:android:001cf5e7d30b27d1ed20c1',
    messagingSenderId: '832631802196',
    projectId: 'kte-lms',
    storageBucket: 'kte-lms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7csYYsmjOQbnkJvvnaW2yYUuFWUUea2Q',
    appId: '1:832631802196:ios:2aa6783f9373fed0ed20c1',
    messagingSenderId: '832631802196',
    projectId: 'kte-lms',
    storageBucket: 'kte-lms.firebasestorage.app',
    iosBundleId: 'com.example.kte',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7csYYsmjOQbnkJvvnaW2yYUuFWUUea2Q',
    appId: '1:832631802196:ios:2aa6783f9373fed0ed20c1',
    messagingSenderId: '832631802196',
    projectId: 'kte-lms',
    storageBucket: 'kte-lms.firebasestorage.app',
    iosBundleId: 'com.example.kte',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTho5UlN1om5mv1shEe3rFNkzYvPD2hP0',
    appId: '1:832631802196:web:e1c7aac987f97e17ed20c1',
    messagingSenderId: '832631802196',
    projectId: 'kte-lms',
    authDomain: 'kte-lms.firebaseapp.com',
    storageBucket: 'kte-lms.firebasestorage.app',
  );
}

// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart';
//
// // ...
//
// await Firebase.initializeApp(
// options: DefaultFirebaseOptions.currentPlatform,
// );
